language: python
python:
  - "3.4_with_system_site_packages"
sudo: required
dist: trusty
env:
  global:
    secure: "iyp8SnisZUQ41PE7Z7+hLBU+REyv8TX3z543hbLQCABSROYhz20QRjbN5MkRe7froAi+2hdWNiTONM3HVqQa9CydqkMGUl9tpDP5Bitpt1k+V/+7BpMwPhFfAi5HBbwvhfcxGidg6Ht9JrbsGb5N1Kf8lwdhJa0P3RP+pkmBk+sYdCxPotlWtf7/GUeg31MpWk4jbQeIqyyKLU1W17zFHM3AslWiHuf6eTwPbE5qzu8yiPP9qihTnNMFso0HLv/I8YMMU5Cb/jIvcu8/rPJrY+kRo9rauuRUzg0iWoG55QHQGqxmN9WH+tSh2xrEZlkaGQtmvgKNsTeJkKup5TAbi3FfHEyKhPKvKYXmpaYZqjXHwLrr4OoJulsD4zcBpQSKtvO3WjPd0CMTQf2muYbwuvEmVGbbYWExO5JSglTTVSWsuiVWvn7G+BR2eFBrCqrXt0YPVrwJc7ct+Z62smhvCaFZGEaA8jSw65qwU0sOaNXQ+epELxKeLlPu0BrjhTNx5Z1k6bw9etwDuCPI0oQZQ7FaM9tNtMiMMg7mhB6QVJxhvWpiJQ+Z/UbwYvNGm2pW2PZ1XPkEa3ysOEjGVcxfd9bPGrD68Ay0Uh5cCp5U1DOCPQXUpY6mfvK8j/tjTv8kL5vRRQCSxpmkN2KtcULzg4EJpodZEzcaCK7/IDaqyws="
notifications:
  email: false
before_install:
  - pip install coveralls
  - pip install codecov
  - sudo apt-get update
  - sudo apt-get install -y xvfb
install:
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-selenium
  - python setup.py install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - py.test -s -v --cov=. --driver Firefox
after_success:
  - coveralls
  - codecov
